# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-02 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Newpaper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='post_id',
        ),
    ]
