# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-03 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Newpaper', '0002_remove_article_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='post_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
