# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-03 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Newpaper', '0003_article_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='post_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='post_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='post_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
